# frozen_string_literal: true

require 'test/unit'
require 'dotenv'
require_relative '../lib/rujira'

class UnitTest < Test::Unit::TestCase
  Dotenv.load

  def random_name
    Array.new(5) { ('A'..'Z').to_a.sample }.join
  end

  def env_var?(var)
    %w[true 1 yes].include?(ENV[var]&.downcase)
  end

  def test_bearer
    return unless env_var? 'RUJIRA_TEST'

    client = Rujira::Client.new('http://localhost:8080')
    client.Myself.get do
      bearer 'SECRET_TOKEN'
    end
  end

  def test_issue_flow # rubocop:disable Metrics/AbcSize,Metrics/MethodLength
    return unless env_var? 'RUJIRA_TEST'

    require 'date'

    now = Date.today
    before = now + 30

    project = random_name
    client = Rujira::Client.new('http://localhost:8080', debug: true)

    client.ServerInfo.get
    name = client.Myself.get['name']

    client.Project.create do
      payload key: project.to_s,
              name: project.to_s,
              projectTypeKey: 'software',
              lead: name
    end
    client.Project.get project.to_s
    client.Issue.create do
      payload fields: {
        project: { key: project.to_s },
        summary: 'BOT: added a new feature.',
        description: 'This task was generated by the bot when creating changes in the repository.',
        issuetype: { name: 'Task' }
      }
      params updateHistory: true
    end

    client.Board.list
    client.Board.get 1

    sprint = client.Sprint.create do
      payload name: 'Bot Sprint',
              originBoardId: 1,
              goal: 'Finish core features for release 1.0',
              autoStartStop: false
    end
    client.Sprint.issue sprint['id'], ["#{project}-1"]

    client.Sprint.replace sprint['id'] do
      payload state: 'future',
              name: 'Bot Sprint',
              originBoardId: 1,
              goal: 'Finish core features for release 1.0',
              startDate: now,
              endDate: before,
              autoStartStop: true
    end

    update = client.Sprint.update sprint['id'] do
      payload name: "Bot Sprint #{project}"
    end

    assert_equal 'Bot Sprint', sprint['name']
    assert_equal "Bot Sprint #{project}", update['name']

    issues = client.Sprint.get_issue sprint['id']

    assert_not_empty issues['issues']

    client.Issue.get "#{project}-1"

    client.Issue.watchers "#{project}-1", name
    search = client.Search.get do
      payload jql: "project = #{project} and status IN (\"To Do\", \"In Progress\") ORDER BY issuekey",
              maxResults: 10,
              startAt: 0,
              fields: %w[id key]
    end
    client.Issue.comment "#{project}-1" do
      payload body: 'Adding a new comment'
    end
    client.Issue.edit "#{project}-1" do
      payload update: {
                labels: [{ add: 'bot' }, { remove: 'some' }]
              },
              fields: {
                assignee: { name: name },
                summary: 'This is a shorthand for a set operation on the summary field'
              }
    end

    sprints = client.Board.sprint 1
    sprints['values'].each do |sprint|
      client.Sprint.delete sprint['id']
    end
    search['issues'].each do |issue|
      client.Issue.delete issue['id'] do
        params deleteSubtasks: true
      end
    end
    client.Project.delete project.to_s

    client.Dashboard.list
    client.Dashboard.get 10_000
  end
end
