---
services:
  jira:
    restart: always
    mem_limit: 2g
    image: atlassian/jira-software
    environment: {}
      # JVM_SUPPORT_RECOMMENDED_ARGS: "-Datlassian.recovery.password=<PASSWORD>"
    ports:
      - 8080:8080
    volumes:
      - 'jira-data:/var/atlassian/application-data/jira'

  db:
    image: postgres
    mem_limit: 128mb  
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jira
    volumes:
      - 'db-data:/var/lib/postgresql/data'

volumes:
  jira-data:
  db-data:
