---
version: '3'
services:
  jira:
    restart: always
    image: atlassian/jira-software
    environment: {}
    ports:
      - 8080:8080
    volumes:
      - 'data:/var/atlassian/application-data/jira'

volumes:
  data:
