# frozen_string_literal: true

require 'dotenv'
require_relative '../lib/rujira'

Dotenv.load

client = Rujira::Client.new('http://localhost:8080', dispatchable: false)

project_name = 'TEST124'
project_key = project_name

issue = client.Issue.create do
  payload fields: {
    project: { key: project_key },
    summary: 'BOT: added a new feature.',
    description: 'This task was generated by the bot when creating changes in the repository.',
    issuetype: { name: 'Task' }
  }
  params updateHistory: true
end

puts "Issue create #{issue.key}"

issue.add_comment('Bot added a comment as obj #1')
comment = issue.add_comment('Bot added a comment as obj #2')
comment.delete

issue.add_comment('Bot added a comment as obj #3')

issue.delete
