# frozen_string_literal: true

require 'dotenv'
require_relative '../lib/rujira'

Dotenv.load

project_name = 'EXAMPLE2'
name = Rujira::Api::Myself.get['name']

begin
  project = Rujira::Api::Project.create do
    payload key: project_name.to_s,
            name: project_name.to_s,
            projectTypeKey: 'software',
            lead: name
  end
rescue StandardError
  projects = Rujira::Api::Project.list
  project = projects.find { |p| p['name'] == project_name }
end

Rujira::Api::Issue.create do
  payload fields: {
    project: { key: project['key'] },
    summary: 'BOT: added a new feature.',
    description: 'This task was generated by the bot when creating changes in the repository.',
    issuetype: { name: 'Task' }
  }
  params updateHistory: true
end

now = Date.today
before = now + 30

sprint = Rujira::Api::Sprint.create do
  payload name: 'Bot Example Sprint',
          originBoardId: 1,
          goal: 'Finish core features for release 1.0',
          startDate: now,
          endDate: before,
          autoStartStop: true
end

Rujira::Api::Sprint.update sprint['id'] do
  payload state: 'active'
end

Rujira::Api::Sprint.issue sprint['id'], ["#{project_name}-1"]
