# frozen_string_literal: true

require 'dotenv'
require_relative '../lib/rujira'

Dotenv.load

client = Rujira::Client.new('http://localhost:8080', dispatchable: true)

project_name = 'TEST124'
project_key = project_name
name = client.Myself.get['name']

project = client.Project.create do
  payload key: project_key,
          name: project_name.to_s,
          projectTypeKey: 'software',
          lead: name
end

client.Issue.create do
  payload fields: {
    project: { key: project['key'] },
    summary: 'BOT: added a new feature.',
    description: 'This task was generated by the bot when creating changes in the repository.',
    issuetype: { name: 'Task' }
  }
  params updateHistory: true
end

now = Date.today
before = now + 30

sprint = client.Sprint.create do
  payload name: 'Bot Example Sprint',
          originBoardId: 1,
          goal: 'Finish core features for release 1.0',
          startDate: now,
          endDate: before,
          autoStartStop: false
end

client.Sprint.update sprint['id'] do
  payload state: 'active'
end

client.Sprint.issue sprint['id'], ["#{project_name}-1"]
